id = "hurl"
name = "Hurl"
version = "0.1.0"
schema_version = 1
authors = ["Thanabodee Charoenpiriyakij <email>"]
description = "Please fill in the description"
repository = "https://github.com/zed-industries/zed"

[grammars.hurl]
repository = "https://github.com/pfeiferj/tree-sitter-hurl"
commit = "ad705af8c44c737bdb965fc081329c50716d2d03"
